### ISSUE TITLE
Monaco: extraLib errors when forking

### ISSUE THREAD

**Issue by CompuIves** [cerebral/codesandbox-client#76]
We register every module as lib to Monaco, for autocompletions. We do this by module id.

When a sandbox gets forked it looks like the module is added again as extra lib, which causes Monaco to crash:

```
Uncaught (in promise) Error: file:///Hello.js already a extra lib
    at e.addExtraLib (http://pr389.cs.lbogdan.tk/public/vs/editor/editor.main.js:39:1227)
    at t.<anonymous> (http://pr389.cs.lbogdan.tk/static/js/common.f72f9f81.js:1:516364)
    at t (http://pr389.cs.lbogdan.tk/static/js/common-sandbox.a6059fb5.js:1:165589)
    at Generator._invoke (http://pr389.cs.lbogdan.tk/static/js/common-sandbox.a6059fb5.js:1:165377)
    at Generator.e.(anonymous function) [as next] (http://pr389.cs.lbogdan.tk/static/js/common-sandbox.a6059fb5.js:1:165768)
    at n (http://pr389.cs.lbogdan.tk/static/js/common-sandbox.a6059fb5.js:1:203088)
    at http://pr389.cs.lbogdan.tk/static/js/common-sandbox.a6059fb5.js:1:203236
    at new Promise (<anonymous>)
    at new r (http://pr389.cs.lbogdan.tk/static/js/common-sandbox.a6059fb5.js:1:67542)
    at t.<anonymous> (http://pr389.cs.lbogdan.tk/static/js/common-sandbox.a6059fb5.js:1:203030)
```

Solution is to dispose all modules when sandbox id changes, then this code gets executed:

https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/components/sandbox/CodeEditor/Monaco.js#L323-L325

**Comment by CompuIves** [comment]
Researched a bit more, I think I can pick this issue up. Looks like the code is there, but maybe not executed?

**Comment by christianalfoni** [comment]
Fix is in PR now
